modLoader="javafml"
loaderVersion="[35,)"
license="MIT"
issueTrackerURL="https://github.com/dodogang/crumbs/issues"

[[mods]]
modId="crumbs"
version="1.0.6"
displayName="Crumbs"
#updateJSONURL=""
displayURL="https://crumbs.dodogang.net"
#logoFile=""
credits="Translations: PandaClod (Spanish), Shadew (Dutch), ro-mod-dev (French), linzexin022 (Chinese)"
authors="Dodo Gang"
description='''
Building mod which adds various blocks tuned to fit with vanilla minecraft.
'''

[[dependencies.crumbs]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.crumbs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="BOTH"
